AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for Security groups
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC ID'

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: Security Group
      GroupDescription: Security group for VPC endpoint
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: '-1'
          CidrIp: 10.0.0.0/16
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: project3-SecurityGroup
Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroup